title:            Jon Stuebe
tagline:          Web Developer
description:      
#Comment out url when working locally to resolve base urls correctly
url: http://jonstuebe.com
#destination: ./html

# Owner/author information
owner:
  name:           Jon Stuebe
  avatar:         avatar.png
  bio:            Web Developer
  email:          
  twitter:        jonstuebe        
  github:         jonstuebe       
  instagram:      jonstuebe     
  codepen:        jonstuebe
  dribbble:       
  disqus:         jonstuebe
  # Plug in your disqus shortname!
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Archive
    url: /archive
  #- title: Github
  #  url: https://github.com/ColeTownsend/Balzac-for-Jekyll
  #  external: true
  #- title: Cole Who?
  #  url: http://coletownsend.com
  #  external: true

paginate: 5
paginate_path: "blog/page/:num"

#ftp_host: s139302.gridserver.com
#ftp_dir: /nfs/c09/h04/mnt/139302/domains/jonstuebe.com/html
#ftp_passive: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Phoenix
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp",".gitignore","Gemfile","Gemfile.lock"]
